### ISSUE TITLE
ane file for the latest version

### ISSUE THREAD

**Issue by jimmymjing** [DigitalStrawberry/ANE-Bugsnag#10]
Hello, I see the latest compiled ane file from released folder was in Dec. 2016. 
Could you please provide a new build for the latest version? Thank you!

**Comment by ecornbower** [comment]
Sure, @marpies can you update the build to be the latest version?

**Comment by marpies** [comment]
@jimmymjing We've added the latest version of the ANE to the releases page.

**Comment by jimmymjing** [comment]
Thank you so much!
