### ISSUE TITLE
new version 5.22.5

### ISSUE THREAD

**Issue by jimmymjing** [DigitalStrawberry/ANE-Bugsnag#12]
Hello, I see that the release version of Bugsnag has been raised to 5.22.5. Is it possible that we could get updated? Many thanks!

**Comment by marpies** [comment]
Hi,

Thanks for the report, we'll look into updating the SDKs.

**Comment by marpies** [comment]
We have updated the SDKs in the [v1.5 release](https://github.com/DigitalStrawberry/ANE-Bugsnag/releases/tag/v1.5).
