### ISSUE TITLE
Not getting Crash Error on iOS

### ISSUE THREAD

**Issue by jrmarkham** [DigitalStrawberry/ANE-Bugsnag#9]
So I added this stack to my initial function (opening function of the app): 

```as3
if(GlobalData.isMobile){
				Bugsnag.init(IOS_BUGSNAG_KEY, ANDROID_BUGSNAG_KEY);
				Bugsnag.autoNotify = true;
				loaderInfo.uncaughtErrorEvents.addEventListener(UncaughtErrorEvent.UNCAUGHT_ERROR, Bugsnag.handleUncaughtError);
				
				Bugsnag.getStackTrace = function(error:*):String {
					if(error is Error)
					{
						return Error(error).getStackTrace();
					}
					return null;
				}
			}
```

I am using the  starling framework. 
I added both  the ANE and SWC. Do I need both? Most ANE don't require an SWC too.

I get zero errors on the Bugsnag Dash Board after a crash. 

Thanks --

**Comment by ecornbower** [comment]
You only need to include the ANE, not the SWC. Your code looks correct to me. @marpies any ideas what might be wrong here?

**Comment by marpies** [comment]
No, the code looks good to me too. Are you sure `GlobalData.isMobile` is `true` when running on your device? When you say crash, do you mean an AS3 error or a native crash? Remember the native crash reports are sent once the app is relaunched.

**Comment by jrmarkham** [comment]
I finally got something through. It took a few builds.
